name: Deploy Main Branch

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        run: |
          npm install -g pnpm
      - name : Install Dependencies
        run: |
          pnpm install;
          pnpm run build;
      - name: Install Necessary Packages
        run: |
          sudo apt install tar -y
      - name: Compressing necessary files
        run: |
          tar -czvf dist.tar.gz dist/ production.config.js package.json;
      - name: Configure SSH
        run: |
            mkdir -p ~/.ssh/
            echo "$SSH_KEY" > ~/.ssh/production_secret.key
            chmod 600 ~/.ssh/production_secret.key
            cat >>~/.ssh/config <<END
            Host production_server
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/production_secret.key
              StrictHostKeyChecking no
            END
        env:
            SSH_USER: ${{ secrets.PRODUCTION_SSH_USER }}
            SSH_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
            SSH_HOST: ${{ secrets.PRODUCTION_SSH_HOST }}
      - name: Copy dist.tar.gz to production server
        run: |
          scp dist.tar.gz production_server:~/scholarship_machine/ && rm dist.tar.gz;
      - name: Install necessary packages on production server
        run: |
          ssh production_server << EOF
            sudo npm install -g pm2 pnpm;
            export PNPM_HOME="$HOME/.local/share/pnpm";
            export PATH="$PNPM_HOME/bin:$PATH";
          EOF
      - name: Clear dist folder on production server
        run: |
          ssh production_server << EOF
          cd ~/scholarship_machine;
          rm -rf dist;
          tar -xzvf dist.tar.gz;
          rm dist.tar.gz;
          EOF
      - name: Install necessary nodejs packages on production server
        run: |
          ssh production_server << EOF
          cd ~/scholarship_machine;
          pnpm install;
          EOF
      - name: Restarting PM2 on production server
        run: |
          ssh production_server << EOF
          cd ~/scholarship_machine;
          ~/.local/share/pnpm/pm2 restart production.config.js;
          EOF


